import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { Check, ChevronDown, CirclePlay, Clock3, FolderGit2, Star, Users } from "lucide-react";
import { Button } from "@/components/Button";
import { CourseCard } from "@/components/CourseCard";
import { CourseDetailFAQ } from "@/components/CourseDetailFAQ";
import { CourseVisual } from "@/components/CourseVisual";
import { Footer } from "@/components/Footer";
import { Navbar } from "@/components/Navbar";
import { courses, getCourseBySlug } from "@/data/courses";

type PageProps = { params: Promise<{ slug: string }> };
export function generateStaticParams() { return courses.map(({ slug }) => ({ slug })); }
export async function generateMetadata({ params }: PageProps): Promise<Metadata> { const course = getCourseBySlug((await params).slug); return course ? { title: course.title, description: course.shortDescription } : {}; }

export default async function CourseDetailPage({ params }: PageProps) {
  const course = getCourseBySlug((await params).slug);
  if (!course) notFound();
  const related = courses.filter((item) => item.id !== course.id).slice(0, 3);
  return <main><Navbar />
    <section className="grid-bg border-b border-[var(--line)]"><div className="shell grid gap-12 py-16 lg:grid-cols-[1fr_420px] lg:py-24"><div><p className="eyebrow text-[var(--mint)]">{course.category} / {course.level}</p><h1 className="mt-6 max-w-4xl text-balance text-5xl font-semibold leading-[.98] sm:text-7xl">{course.title}</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-[var(--muted)]">{course.description}</p><div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-sm"><span className="flex items-center gap-2"><Star size={16} fill="var(--yellow)" className="text-[var(--yellow)]" />{course.rating} rating</span><span className="flex items-center gap-2"><Users size={16} className="text-[var(--mint)]" />{course.students.toLocaleString()} students</span><span className="flex items-center gap-2"><Clock3 size={16} className="text-[var(--mint)]" />{course.duration}</span><span className="flex items-center gap-2"><FolderGit2 size={16} className="text-[var(--mint)]" />{course.projects} projects</span></div><p className="mt-8 text-sm text-[var(--muted)]">Taught by <strong className="text-white">{course.instructor}</strong></p></div>
      <aside className="surface self-start"><CourseVisual course={course} compact /><div className="p-6"><p className="text-4xl font-bold">${course.price}</p><Button href={`/checkout/${course.slug}`} className="mt-5 w-full" arrow>Enroll now</Button><button className="focus-ring mt-3 flex w-full items-center justify-center gap-2 border border-[var(--line)] py-3 text-sm font-bold hover:border-white"><CirclePlay size={17} />Watch preview</button><p className="mt-4 text-center text-xs text-[var(--muted)]">30-day learning guarantee</p></div></aside></div></section>

    <section className="section-pad shell grid gap-14 lg:grid-cols-[1.3fr_.7fr]"><div><h2 className="text-3xl font-bold">What you&apos;ll learn</h2><div className="mt-8 grid gap-4 sm:grid-cols-2">{course.outcomes.map((outcome) => <div className="flex gap-3 border-t border-[var(--line)] pt-4" key={outcome}><Check className="mt-1 shrink-0 text-[var(--mint)]" size={17} /><span className="leading-6">{outcome}</span></div>)}</div></div><aside><h2 className="text-3xl font-bold">Core skills</h2><div className="mt-7 flex flex-wrap gap-2">{course.skills.map((skill) => <span className="border border-[var(--line)] bg-[var(--panel)] px-3 py-2 text-sm" key={skill}>{skill}</span>)}</div></aside></section>

    <section className="section-pad border-y border-[var(--line)] bg-[#0b0f0e]"><div className="shell grid gap-14 lg:grid-cols-[1.3fr_.7fr]"><div><p className="eyebrow text-[var(--mint)]">Curriculum</p><h2 className="mt-4 text-4xl font-bold">From first concept to final deploy.</h2><div className="mt-10">{course.modules.map((module, index) => <details className="border-t border-[var(--line)] last:border-b" key={module.title} open={index === 0}><summary className="focus-ring flex cursor-pointer items-center justify-between gap-5 py-6"><span><span className="mr-4 font-mono text-sm text-[var(--mint)]">{String(index + 1).padStart(2, "0")}</span><strong>{module.title}</strong></span><ChevronDown size={19} className="text-[var(--muted)]" /></summary><div className="pb-6 pl-0 sm:pl-12">{module.lessons.map((lesson) => <div className="flex items-center justify-between border-t border-white/5 py-3 text-sm" key={lesson.title}><span className="flex items-center gap-3"><CirclePlay size={15} className="text-[var(--muted)]" />{lesson.title}{lesson.preview && <span className="bg-[var(--mint)] px-2 py-1 text-[10px] font-bold text-[var(--ink)]">PREVIEW</span>}</span><span className="text-[var(--muted)]">{lesson.duration}</span></div>)}</div></details>)}</div></div><aside><h2 className="text-2xl font-bold">Projects you&apos;ll ship</h2><ol className="mt-6 space-y-4">{course.projectNames.map((project, i) => <li className="surface flex items-center gap-4 p-4" key={project}><span className="font-mono text-xs text-[var(--mint)]">0{i + 1}</span><strong className="text-sm">{project}</strong></li>)}</ol><h2 className="mt-12 text-2xl font-bold">Requirements</h2><ul className="mt-5 space-y-3">{course.requirements.map((requirement) => <li className="flex gap-3 text-sm leading-6 text-[var(--muted)]" key={requirement}><Check className="mt-1 shrink-0 text-[var(--mint)]" size={15} />{requirement}</li>)}</ul></aside></div></section>

    <section className="section-pad shell"><div className="grid gap-10 border-b border-[var(--line)] pb-20 lg:grid-cols-[.6fr_1.4fr]"><div><div className="grid size-24 place-items-center bg-[var(--paper)] text-2xl font-black text-[var(--ink)]">{course.instructor.split(" ").map((name) => name[0]).join("")}</div><p className="eyebrow mt-5 text-[var(--muted)]">Your instructor</p></div><div><h2 className="text-4xl font-bold">{course.instructor}</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-[var(--muted)]">Senior engineer and product builder who teaches the habits behind maintainable software: clear thinking, thoughtful tradeoffs, and shipping work that holds up outside a tutorial.</p></div></div><CourseDetailFAQ /><h2 className="mt-20 text-3xl font-bold">Keep building</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{related.map((item) => <CourseCard course={item} key={item.id} />)}</div></section><Footer />
  </main>;
}
