"use client";

import { LockKeyhole } from "lucide-react";
import { FormEvent, useState } from "react";

export function PaymentForm() {
  const [submitted, setSubmitted] = useState(false);
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitted(true); }
  return <form className="surface p-6 sm:p-8" onSubmit={submit} data-reveal="right"><div className="mb-7 flex items-center justify-between border-b border-[var(--line)] pb-6"><div><p className="eyebrow text-[var(--mint)]">Payment details</p><h2 className="mt-2 text-2xl font-bold">Complete your order</h2></div><LockKeyhole className="text-[var(--muted)]" /></div><label className="block"><span className="mb-2 block text-sm font-bold">Name on card</span><input required autoComplete="cc-name" placeholder="Alex Morgan" className="focus-ring h-12 w-full border border-[var(--line)] bg-[#0b0f0e] px-4 outline-none placeholder:text-[#68716e]" /></label><label className="mt-5 block"><span className="mb-2 block text-sm font-bold">Card number</span><input required inputMode="numeric" autoComplete="cc-number" placeholder="1234 5678 9012 3456" className="focus-ring h-12 w-full border border-[var(--line)] bg-[#0b0f0e] px-4 font-mono outline-none placeholder:text-[#68716e]" /></label><div className="mt-5 grid grid-cols-2 gap-4"><label><span className="mb-2 block text-sm font-bold">Expiration</span><input required inputMode="numeric" autoComplete="cc-exp" placeholder="MM / YY" className="focus-ring h-12 w-full border border-[var(--line)] bg-[#0b0f0e] px-4 font-mono outline-none placeholder:text-[#68716e]" /></label><label><span className="mb-2 block text-sm font-bold">CVC</span><input required inputMode="numeric" autoComplete="cc-csc" placeholder="123" className="focus-ring h-12 w-full border border-[var(--line)] bg-[#0b0f0e] px-4 font-mono outline-none placeholder:text-[#68716e]" /></label></div><button className="btn-motion focus-ring mt-7 flex min-h-12 w-full items-center justify-center gap-2 bg-[var(--mint)] px-5 font-bold text-[var(--ink)] hover:bg-white" type="submit"><LockKeyhole size={16} />Complete purchase</button><p className="mt-4 text-center text-xs leading-5 text-[var(--muted)]">Checkout is a UI preview. No card data is submitted or stored.</p>{submitted && <p className="form-alert mt-5 border border-[var(--yellow)]/40 bg-[var(--yellow)]/10 p-3 text-sm text-[var(--yellow)]" role="status">Payment is not configured. Connect Stripe before accepting purchases.</p>}</form>;
}
